apiVersion: apps/v1
kind: Deployment
metadata:
  name: fidelity-ui-deployment
  namespace: fidelity-ui
  labels:
    app: fidelity-ui
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: fidelity-ui
  template:
    metadata:
      labels:
        app: fidelity-ui
    spec:
      containers:
        - name: fidelity-ui-container
          image: fidelity-ui:20250525-1409
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
