apiVersion: v1
kind: Service
metadata:
  name: fidelity-ui-service
  namespace: fidelity-ui
spec:
  type: NodePort
  selector:
    app: fidelity-ui
  ports:
    - name: ui
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30082
